import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:syncfusion_flutter_calendar/calendar.dart';
import 'package:uuid/uuid.dart';

import 'Professor.dart';
import 'Room.dart';

class CalendarEvent extends Appointment {
  @override
  final String id;
  final String title;
  final String description;
  final Professor professor;
  final Room room;

  CalendarEvent({
    required this.id,
    required this.title,
    required this.description,
    required this.professor,
    required this.room,
    required DateTime startTime,
    required DateTime endTime,
  }) : super(
    startTime: startTime,
    endTime: endTime,
    subject: title,
  );

  factory CalendarEvent.autogenerated({
    required String title,
    required String description,
    required Professor professor,
    required Room room,
    required DateTime startTime,
    required DateTime endTime,
  }) {
    String generatedId = Uuid().v4();

    return CalendarEvent(
      id: generatedId,
      title: title,
      description: description,
      professor: professor,
      room: room,
      startTime: startTime,
      endTime: endTime,
    );
  }

  factory CalendarEvent.fromMap(Map<String, dynamic> map) {
    return CalendarEvent(
      id: map['id'],
      title: map['title'] ?? '',
      description: map['description'] ?? '',
      professor: Professor.fromMap(map['professor'] ?? {}),
      room: Room.fromMap(map['room'] ?? {}),
      startTime: (map['startTime'] as Timestamp?)?.toDate() ?? DateTime.now(),
      endTime: (map['endTime'] as Timestamp?)?.toDate() ?? DateTime.now(),
    );
  }

  @override
  List<Object?> get props => [id, startTime, endTime, title, description];
}
