import 'package:uuid/uuid.dart';

class Room {
  final String id;
  final String name;
  final String building;
  final String floor;
  final List<List<int>> seats;

  Room({
    required this.id,
    required this.name,
    required this.building,
    required this.floor,
    required this.seats,
  });

  factory Room.autogenerated({
    required String name,
    required String building,
    required String floor,
    required List<List<int>> seats,
  }) {
    String generatedId = Uuid().v4();

    return Room(
      id: generatedId,
      name: name,
      building: building,
      floor: floor,
      seats: seats,
    );
  }
}
